# Refer to the following for details:
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

version: 3

project:
  id: custom+14712/github.com/y-iihoshi/ThScoreFileConverter
