version: '{build}'
branches:
  only:
    - master

image: Visual Studio 2017
configuration:
  - Release
environment:
  PYTHON: C:\Python36-x64
install:
  - cmd: >-
      curl -O https://download.visualstudio.microsoft.com/download/pr/100473929/045b56eb413191d03850ecc425172a7d/vs_Community.exe

      vs_Community.exe modify --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community" --add Microsoft.VisualStudio.Workload.Python --quiet --wait

      %PYTHON%\python -m pip install -U pip

      %PYTHON%\python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: >-
      xcopy ThScoreFileConverter\bin\%CONFIGURATION% publish /e /i /q

      xcopy ManualGenerator\_build\html publish\doc /e /i /q

      xcopy template publish\template /e /i /q

artifacts:
  - path: publish
    name: ThScoreFileConverter
