version: '{build}'

image: Visual Studio 2017
configuration:
  - Release
environment:
  PYTHON: C:\Python36-x64
  VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
install:
  - cmd: curl -LO https://aka.ms/vs/15/release/vs_community.exe
  - cmd: vs_community.exe modify --installPath "%VSINSTALLDIR%" --add Microsoft.VisualStudio.Workload.Python --quiet --wait
  - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - cmd: python --version
  - cmd: python -m pip install -U pip
  - cmd: python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build:
  project: ThScoreFileConverter.sln
  parallel: true
  verbosity: minimal
after_build:
  - cmd: xcopy ThScoreFileConverter\bin\%CONFIGURATION% publish /e /i /q
  - cmd: xcopy ManualGenerator\_build\html publish\doc /e /i /q
  - cmd: xcopy template publish\template /e /i /q

artifacts:
  - path: publish
    name: ThScoreFileConverter

deploy:
  provider: GitHub
  auth_token:
    secure: XBLZ1KuCOmvayGOFMZwYC+QyZxCmr0og6vKt53trP9I3WgF77pN+aVZvim2UP2Dm
  description: ''
  on:
    appveyor_repo_tag: true

for:
- branches:
    except:
    - master
  configuration: Debug
  environment:
    CODECOV_TOKEN:
      secure: yXCs8FBlLFVrjJ3nOjqOVGDV892aCCsBvlT7yF6xEFKC1Opq2mJuOt0gR4A7xBkS
  test_script:
    - cmd: OpenCover.bat %CONFIGURATION% coverage.xml
    - cmd: .\packages\Codecov.1.0.3\tools\codecov.exe -f coverage.xml -t %CODECOV_TOKEN%
  deploy: off
