version: '{build}'

image: Visual Studio 2019
configuration:
  - Debug
  - Release
environment:
  PYTHON: C:\Python38-x64
  VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  CODECOV_TOKEN:
    secure: yXCs8FBlLFVrjJ3nOjqOVGDV892aCCsBvlT7yF6xEFKC1Opq2mJuOt0gR4A7xBkS
  matrix:
    - TARGET_FRAMEWORK: net48
    - TARGET_FRAMEWORK: netcoreapp3.1
install:
  - cmd: |
      curl -LO https://aka.ms/vs/16/release/vs_community.exe
      vs_community.exe modify --installPath "%VSINSTALLDIR%" --add Microsoft.VisualStudio.Workload.Python --quiet --norestart --wait
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
      python --version
      python -m pip install -U pip
      python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build_script:
  - cmd: |
      set LOGGER="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      msbuild ThScoreFileConverter.sln /m /verbosity:minimal /p:TargetFrameworks=%TARGET_FRAMEWORK% /logger:%LOGGER%
after_build:
  - cmd: |
      xcopy ThScoreFileConverter\bin\%CONFIGURATION%\%TARGET_FRAMEWORK% publish\%TARGET_FRAMEWORK% /e /i /q
      xcopy ManualGenerator\_build\html publish\%TARGET_FRAMEWORK%\doc /e /i /q
      xcopy ThScoreFileConverter\Templates publish\%TARGET_FRAMEWORK%\template /e /i /q
      del publish\%TARGET_FRAMEWORK%\template\*.tt* /q

before_test:
  - ps: .\PrintTestEnvironment.ps1
test_script:
  - ps: |
      & .\OpenCover.ps1 ThScoreFileConverterTests\bin\%CONFIGURATION%\%TARGET_FRAMEWORK%\coverage.xml
      & .\Codecov.ps1 ThScoreFileConverterTests\bin\%CONFIGURATION%\%TARGET_FRAMEWORK%\coverage.xml

artifacts:
  - path: publish\%TARGET_FRAMEWORK%
    name: ThScoreFileConverter.%TARGET_FRAMEWORK%

deploy:
  provider: GitHub
  auth_token:
    secure: XBLZ1KuCOmvayGOFMZwYC+QyZxCmr0og6vKt53trP9I3WgF77pN+aVZvim2UP2Dm
  description: ''
  on:
    appveyor_repo_tag: true

for:
-
  branches:
    except:
      - master
  deploy: off
-
  matrix:
    only:
      - configuration: Debug
  deploy: off
-
  matrix:
    only:
      - configuration: Release
  test: off
