version: '{build}'

image: Visual Studio 2017
configuration:
  - Debug
  - Release
environment:
  PYTHON: C:\Python36-x64
  VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
  CODECOV_TOKEN:
    secure: yXCs8FBlLFVrjJ3nOjqOVGDV892aCCsBvlT7yF6xEFKC1Opq2mJuOt0gR4A7xBkS
install:
  - cmd: |
      curl -LO https://aka.ms/vs/15/release/vs_community.exe
      vs_community.exe modify --installPath "%VSINSTALLDIR%" --add Microsoft.VisualStudio.Workload.Python --quiet --wait
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
      python --version
      python -m pip install -U pip
      python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build:
  project: ThScoreFileConverter.sln
  parallel: true
  verbosity: minimal
after_build:
  - cmd: |
      xcopy ThScoreFileConverter\bin\%CONFIGURATION% publish /e /i /q
      xcopy ManualGenerator\_build\html publish\doc /e /i /q
      xcopy templates publish\template /e /i /q

before_test:
  - ps: .\PrintTestEnvironment.ps1
test_script:
  - ps: |
      & .\OpenCover.ps1 coverage.xml
      & .\Codecov.ps1 coverage.xml

artifacts:
  - path: publish
    name: ThScoreFileConverter

deploy:
  provider: GitHub
  auth_token:
    secure: XBLZ1KuCOmvayGOFMZwYC+QyZxCmr0og6vKt53trP9I3WgF77pN+aVZvim2UP2Dm
  description: ''
  on:
    appveyor_repo_tag: true

for:
-
  branches:
    except:
      - master
  deploy: off
-
  matrix:
    only:
      - configuration: Debug
  deploy: off
-
  matrix:
    only:
      - configuration: Release
  test: off
