name: CI

on: [push, pull_request]

# Workaround indicated by https://github.com/dotnet/sdk/issues/10878
env:
  MSBUILDSINGLELOADCONTEXT: 1

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        target-framework: [net48, netcoreapp3.1]

    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Cache Python packages
      uses: actions/cache@v1.1.2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('ManualGenerator/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Setup Python environment
      uses: actions/setup-python@v2.1.3

    - name: Restore Python packages
      run: |
        python -m pip install -U pip
        python -m pip install -r ManualGenerator\requirements.txt

    - name: Cache NuGet packages
      uses: actions/cache@v1.1.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ matrix.target-framework }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ matrix.target-framework }}-
          ${{ runner.os }}-nuget-

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ThScoreFileConverter.sln

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: >
        msbuild ThScoreFileConverter.sln /m /verbosity:minimal
        /p:Configuration=${{ matrix.configuration }}
        /p:TargetFrameworks=${{ matrix.target-framework }}

    - name: Generate coverage report
      run: >
        dotnet test ThScoreFileConverterTests
        /p:Configuration=${{ matrix.configuration }}
        /p:TargetFrameworks=${{ matrix.target-framework }}
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=opencover
        /p:CoverletOutput=coverage.xml
      if: matrix.configuration == 'Debug'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ThScoreFileConverterTests/coverage.${{ matrix.target-framework }}.xml
      if: matrix.configuration == 'Debug'

    - name: Collect artifacts
      run: |
        xcopy ThScoreFileConverter\bin\${{ matrix.configuration }}\${{ matrix.target-framework }} publish\${{ matrix.target-framework }} /e /i /q
        xcopy ManualGenerator\_build\html publish\${{ matrix.target-framework }}\doc /e /i /q
        xcopy ThScoreFileConverter\Templates publish\${{ matrix.target-framework }}\template /e /i /q
        del publish\${{ matrix.target-framework }}\template\*.tt* /q
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ThScoreFileConverter.${{ matrix.target-framework }}
        path: publish\${{ matrix.target-framework }}
