name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target-framework: [net6.0-windows, net8.0-windows]

    uses: ./.github/workflows/_build.yml
    with:
      python-version: '3.x'
      dotnet-configuration: 'Release'
      dotnet-target-framework: ${{ matrix.target-framework }}
      artifact-name: 'ThScoreFileConverter-${{ github.ref_name }}-${{ matrix.target-framework }}'

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact (net6.0)
        uses: actions/download-artifact@v4
        with:
          name: 'ThScoreFileConverter-${{ github.ref_name }}-net6.0-windows'
          path: 'artifacts/net6.0'
      - name: Download artifact (net8.0)
        uses: actions/download-artifact@v4
        with:
          name: 'ThScoreFileConverter-${{ github.ref_name }}-net8.0-windows'
          path: 'artifacts/net8.0'
      - name: Zip artifacts
        run: |
          7z a ThScoreFileConverter-${{ github.ref_name }}-net6.0.zip -r ./artifacts/net6.0/*
          7z a ThScoreFileConverter-${{ github.ref_name }}-net8.0.zip -r ./artifacts/net8.0/*
      - name: Create GitHub release as draft
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: true
          files: |
            ThScoreFileConverter-${{ github.ref_name }}-net6.0.zip
            ThScoreFileConverter-${{ github.ref_name }}-net8.0.zip
