name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target-framework: [net48, net6.0-windows]

    uses: ./.github/workflows/_build.yml
    with:
      python-version: '3.x'
      dotnet-configuration: 'Release'
      dotnet-target-framework: ${{ matrix.target-framework }}
      artifact-name: 'ThScoreFileConverter-${{ github.ref_name }}-${{ matrix.target-framework }}'

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: 'ThScoreFileConverter-${{ github.ref_name }}-${{ matrix.target-framework }}'
          path: 'artifact'
      - name: Zip artifact
        run: 7z a ThScoreFileConverter-${{ github.ref_name }}-${{ matrix.target-framework }}.zip -r ./artifact/*
      - name: Create GitHub release as draft
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: true
          files: 'ThScoreFileConverter-${{ github.ref_name }}-${{ matrix.target-framework }}.zip'
